config/routes.rb
Rails.application.routes.draw do
  get 'product/new'

  resources :users
  resources :products


  #static Pages
  root 'static_pages#home'
  get  '/contact',    to: 'static_pages#contact'
  get  '/about',   to: 'static_pages#about'

  #users
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  #sessions for log in and log out
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  mount_uploader :picture, PictureUploader
  validate  :picture_size


private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
    before_save { email.downcase! }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name,  presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :find_product, only: [:show, :edit, :update, :destroy]

def index
    if params[:category].blank?
      @products = Product.all.order("created_at DESC")
  else
      @category_id = Category.find_by(name: params[:category]).id
      @Products = Product.where(:category_id => @category_id).order("created_at DESC")
  end
end

def show
  @product = Product.find(params[:id])
  end

  def new
    @product = current_user.products.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create
      @product = current_user.products.build(product_params)
      @product.category_id = params[:category_id]
      if @product.save
        redirect_to products_path
      else
        render 'new'
      end
    end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
  @product.category_id = params[:category_id]
  if @product.update(product_params)
    redirect_to products_path(@product)
  else
    render 'edit'
  end
end


  def destroy
    @product.destroy
    redirect_to products_path
  end


  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :picture)
  end

  def find_product
    @product = Product.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
   user = User.find_by(email: params[:session][:email].downcase)
  #  debugger
  # if user is found
  if user && user.authenticate( params[:session][:password] )
    # not rendering
    flash[:success] = 'Success login yay!'
    log_in(user)

    redirect_to user
  else
    # show error notice
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end
end

def destroy
  log_out if logged_in?
  # add flash after log out
  flash[:info] = 'Bye bye'
  redirect_to root_url
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #setting default users
  before_action :set_user,      only:   [:show, :edit, :update, :destroy]
  #check if alredy logged in
  before_action :require_login, only:   [:edit, :update, :destroy]
  #check if correct user
  before_action :correct_user,  except: [:index, :new, :show, :create ]

  before_action :require_logout,  only: [:new]


  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new(user_params)
  if @user.save
    log_in @user
    flash[:success] = "Welcome to the Sample App!"
    redirect_to @user
  else
    render 'new'
  end
end

   def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  def set_user
        @user = User.find(params[:id])
      end


      # Confirms the correct user.
      def correct_user
        @user = User.find(params[:id])

        unless current_user?(@user)
          flash[:warning] = "You are not the actual user"
          redirect_to root_url
        end
      end

      def require_login
      #check if the user is logged in or not
      unless logged_in?
        flash[:danger] = "You need to log in first!"
        redirect_to root_url # halts request cycle
      end
    end

      def require_logout
        if logged_in?
          flash.now[:warning] = "You must logged out to create a new user"
          redirect_to root_url
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
      session[:user_id] = user.id
    end

    # Get current user from session id, always check from the latest session
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    # check if passed user is current_user
    def current_user?(user)
      user == current_user
    end

    # check if current user is nil
    def logged_in?
      current_user
    end

    def log_out
      session.delete(:user_id) #delete part of the session
      @current_user = nil #set current_user to empty again
    end
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Red Mart by Jonathan
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Sign Up", signup_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "THE REDMART", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Sell with us", new_product_path %></li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>

        <% if logged_in? %>
                  <li><%= link_to "Users", users_path %></li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               Account <b class="caret"></b>
             </a>
             <ul class="dropdown-menu">
               <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
               <li class="divider"></li>
               <li>
                 <%= link_to "Log out", logout_path, method: "delete" %>
               </li>
             </ul>
           </li>
         <% else %>
           <li><%= link_to "Log in", login_path %></li>
         <% end %>
       </ul>
     </nav>
   </div>
 </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Redmart Groceries</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "select a category")%>
<% f.file_field :product_img %>
<%= f.label :"Product Name" %>
<%= f.text_field :name %>
<%= f.label :"Description" %>
<%= f.text_field :description %>
<%= f.label :"Price" %>
<%= f.text_field :price%>
<%= f.label :"Picture" %>
<%= f.file_field :picture %>
<%= f.submit "Submit", class: "btn btn-primary" %>
<%end%>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= form_for @product, :html => { :multipart => true } do |f| %>
<%= f.select :category_id, @categories%>
<% f.file_field :product_img %>
<%= f.label :"Product Name" %>
<%= f.text_field :name %>
<%= f.label :"Description" %>
<%= f.text_field :description %>
<%= f.label :"Price" %>
<%= f.text_field :price %>
<%= f.label :"Picture" %>
<%= f.file_field :picture %>

<%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>

<%= link_to "Sell your product", new_product_path %>

app/views/products/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<h1>THe Online Marketplace to sell and buy your groceries</h1>

<div>
  <% if logged_in? %>
  <h2><%= link_to "Upload your products now and start selling with Redmart!", new_product_path %></h2>
  <%end%>
</div>

<% @products.each do |product| %>

<table class="table table-striped">

<thead>
  <tr>
    <th>Image</th>
    <th>Product Name</th>
    <th>Price(SGD)</th>
    <th>Description</th>
    <th>Buy</th>
  </tr>
</thead>

<tbody>


  <tr>
    <td>
      <%= image_tag product.picture.url if product.picture? %>
    </td>

    <td>
      <%= link_to product.name, product_path(product) %>
    </td>

    <td>
      <%= product[:price]%>
    </td>

    <td>
      <%= product[:description]%>
    </td>


    <td>
    <%= link_to "Buy Now", '#' %>
    </td>

  </tr>
</tbody>
</table>

<%end%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<p>
 <strong>Name:</strong>
 <%= @product.name %>
</p>

<p>
 <strong>Price(SGD):</strong>
 <%= @product.price %>
</p>

<p>
 <%= image_tag @product.picture.url%>
</p>

<%= link_to "Back", products_path(@product) %>

<% if current_user?(@product.user)%>
<%= link_to "Edit", edit_product_path(@product) %>
<%= link_to "Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure?"} %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_signin.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vestibulum lectus turpis, ultricies porta nisl varius et. Mauris in sodales turpis. Morbi nulla arcu, fringilla id gravida in, semper sit amet tellus. Donec bibendum urna eu porta mattis. Vestibulum eu nulla imperdiet nulla mattis posuere nec sit amet augue. Vestibulum ultrices augue eget blandit molestie. Sed ac facilisis lorem. Suspendisse non sodales ipsum, ullamcorper venenatis ex. Fusce nisl erat, accumsan ut ipsum vitae, gravida faucibus lorem. Integer venenatis at felis tempor congue. Quisque quam leo, sodales dictum tristique in, fermentum eu est. Curabitur feugiat pellentesque mollis. Donec rhoncus massa ac vestibulum porttitor. Proin sit amet porta velit, id sollicitudin risus.</p>

  <p>Donec ac porttitor magna. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis nec fermentum mauris. Proin venenatis, urna eu vestibulum egestas, ex nulla feugiat ipsum, vel ornare neque velit ut mauris. Sed urna urna, mollis ultrices mattis nec, pulvinar non dolor. Fusce ac ex turpis. Nam non aliquam ex. Nunc vitae nisi facilisis purus eleifend lacinia. Sed accumsan tellus sit amet massa tincidunt, tempor ultricies lectus blandit. Vestibulum eu consequat lorem. Proin eget molestie diam. Proin posuere elit magna, vitae tincidunt enim lobortis et. Sed vitae orci in elit condimentum pulvinar. Maecenas ornare non nibh eu luctus.</p>

  <p>Etiam at mollis diam, sagittis molestie elit. Maecenas interdum laoreet tellus, vel ultricies ligula mattis vel. Proin at lacus vel nulla bibendum aliquam quis id justo. Vivamus mi quam, accumsan eget finibus in, auctor ac lectus. Nulla in augue eget massa luctus egestas. Quisque cursus pharetra leo aliquam egestas. Nam at molestie est. Nam non tristique nibh. Fusce et bibendum ligula. Vestibulum dictum laoreet venenatis. Mauris elementum tellus in mi vehicula, id commodo nulla bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas convallis molestie ante, iaculis euismod dolor finibus quis. Pellentesque eu eleifend urna, sit amet condimentum est. Donec imperdiet varius porttitor. Duis ac hendrerit elit.</p>

  

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>
<h2>Our Location: Somewhere in Singapore, Plaza Singapore</h2>

  <p>Etiam at mollis diam, sagittis molestie elit. Maecenas interdum laoreet tellus, vel ultricies ligula mattis vel. Proin at lacus vel nulla bibendum aliquam quis id justo. Vivamus mi quam, accumsan eget finibus in, auctor ac lectus. Nulla in augue eget massa luctus egestas. Quisque cursus pharetra leo aliquam egestas. Nam at molestie est. Nam non tristique nibh. Fusce et bibendum ligula. Vestibulum dictum laoreet venenatis. Mauris elementum tellus in mi vehicula, id commodo nulla bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas convallis molestie ante, iaculis euismod dolor finibus quis. Pellentesque eu eleifend urna, sit amet condimentum est. Donec imperdiet varius porttitor. Duis ac hendrerit elit.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron" id="jump">
  <h1>Welcome to Red Mart</h1>

  <h2>
    Freshest Groceries at your doorstep
  </h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<div>
  <h2>Notice to Sellers - Sign Up or Login now to upload your sale items</h2>
</div>


<% if current_user?(@user) %>
<%= render 'shared/signin' %>
<% else %>
<img src="https://allottspta.files.wordpress.com/2015/04/welcome.jpg" style="width:1100px;height:228px;">
<h1>Hello Stranger!</h1>
<p>Etiam at mollis diam, sagittis molestie elit. Maecenas interdum laoreet tellus, vel ultricies ligula mattis vel. Proin at lacus vel nulla bibendum aliquam quis id justo. Vivamus mi quam, accumsan eget finibus in, auctor ac lectus. Nulla in augue eget massa luctus egestas. Quisque cursus pharetra leo aliquam egestas. Nam at molestie est. Nam non tristique nibh. Fusce et bibendum ligula. Vestibulum dictum laoreet venenatis. Mauris elementum tellus in mi vehicula, id commodo nulla bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas convallis molestie ante, iaculis euismod dolor finibus quis. Pellentesque eu eleifend urna, sit amet condimentum est. Donec imperdiet varius porttitor. Duis ac hendrerit elit.</p>
<%end%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="gravatar_edit">
  <%= gravatar_for @user %>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
     <%= render user %>
  <% end %>
</ul>
<p>hello</p>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<% if current_user?(@user) %>
  <%= link_to "Edit", edit_user_path %>
  | <%= link_to "delete", @user, method: :delete,
                                data: { confirm: "You sure?" } %>

<% end %>